# Generated by Django 4.2.24 on 2026-01-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minishop_backend_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="availability_status",
            field=models.CharField(default="In Stock", max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
    ]
