# Generated by Django 4.2.24 on 2026-01-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minishop_backend_app', '0002_product_availability_status_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
